### PR TITLE
Option for presenting list

### PR DESCRIPTION
**Pull request by panlybero**
Added an option for providing a list of presenting input values. Input file is a csv with at least one column named "hospitalized" that contains the presenting values for every timestep. Length of simulation is determined by the length of the "hospitalized" column.

### CODE REVIEW

**Comment by panlybero** [comment]
Also need some help with stting up the snakefile for this when possible. Thanks!

**Comment by michaelchughes** [comment]
Great work! Some ideas:
* Naming: Can we avoid hardcoding new vocabulary like "hospitalized" and instead use "num_Presenting", so that it is more obvious how that column aligns with our states
* Require provided CSV file to have two columns: "timestep" and "num_Presenting"
This way, we can lookup specific timesteps, and don't need to remake CHIME output CSVs every day (e.g. we can reuse the same CSV file of CHIME output as if t=0 means 2020/04/04 or 2020/04/06)

* Allow provided CSV file name to depend on random state, using syntax "{random_seed}" which means we replace that string with the random_seed parameter
* Would prefer if the file path is specified completely in params.json , this way we can be sure we track it

I'm working on a revised PR with these edits, will ping here soon when done

**Comment by panlybero** [comment]
should we merge the changes?

**Comment by michaelchughes** [comment]
I just pushed some edits. Added a proper working example here:
https://github.com/tufts-ml/covid19-forecasting/tree/panlybero-patch-1/workflows/simple_example_num_presenting_from_file

Usage:
```
Simple example of reading in from presenting-random_seed=101.csv
$ snakemake --cores 1 --use-conda simple

Example where we can read in a custom file for each random_seed
snakemake --cores 1 all_wildcard_results
```

**Comment by michaelchughes** [comment]
@panlybero I've verified this on my laptop and on the HPC cluster. I recommend Merging.

OK with you?

**Comment by panlybero** [comment]
sounds good!

**Pull request merged**
